export const FETCH_AUTHSTATUS = 'FETCH_AUTHSTATUS';
export const FETCH_MODEL = 'FETCH_MODEL';
export const FETCH_MODELSTREAMS = 'FETCH_MODELSTREAMS';
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_SIDEBAR = "FETCH_SIDEBAR";